name: Recipes backend

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  workflow_dispatch:



permissions:
  contents: read
  id-token: write

jobs:

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    env:
      ENV: prod
      DBUSER: ${{ secrets.DBUSER }}
      DBPASS: ${{ secrets.DBPASS }}
      DBHOST: ${{ secrets.DBHOST }}
      DBNAME: ${{ secrets.DBNAMEPROD }}
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: python-app
        path: .
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2 
      id: deploy-to-webapp
      with:
        app-name: 'jrubiales-assignment-backend-prod'

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: build
    env:
      ENV: dev
      DBUSER: ${{ secrets.DBUSER }}
      DBPASS: ${{ secrets.DBPASS }}
      DBHOST: ${{ secrets.DBHOST }}
      DBNAME: ${{ secrets.DBNAMEDEV }}
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: python-app
        path: .
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      id: deploy-to-webapp
      with:
        app-name: 'jrubiales-assignment-backend-dev'